CREATE TABLE contact (
	contact_system_code varchar(16) NOT NULL,
	contact_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(16) NOT NULL,
	last_name varchar(16) NOT NULL,
	status varchar(1) NOT NULL DEFAULT 'A',
	created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	modified_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	vers integer NULL,
	CONSTRAINT contact_pk PRIMARY KEY (contact_id),
	CONSTRAINT contact_contact_system_fk FOREIGN KEY (contact_system_code) REFERENCES contact_system(contact_system_code) ON DELETE CASCADE
);
CREATE UNIQUE INDEX contact_idx1 ON contact (contact_system_code, contact_id);

COMMENT ON TABLE contact IS 'Contact';
COMMENT ON COLUMN contact.contact_system_code IS 'Contact System Code';
COMMENT ON COLUMN contact.contact_id IS 'Contact ID';
COMMENT ON COLUMN contact.first_name IS 'First Name';
COMMENT ON COLUMN contact.last_name IS 'Last Name';
COMMENT ON COLUMN contact.status IS 'Status';
COMMENT ON COLUMN contact.created_at IS 'Created At';
COMMENT ON COLUMN contact.modified_at IS 'Updated At';
COMMENT ON COLUMN contact.vers IS 'Vers';