CREATE TABLE contact_communication_method (
	contact_system_code varchar(16) NOT NULL,
	contact_id integer NOT NULL,
	contact_communication_method_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	communication_method_code varchar(16) NOT NULL,
	communication_method_label_code varchar(8) NOT NULL,
	format_value varchar(1024) NULL,
	is_default bool NOT NULL DEFAULT false,
	status varchar(1) NOT NULL DEFAULT 'A',
	created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	modified_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	vers integer NULL,
	CONSTRAINT contact_communication_method_pk PRIMARY KEY (contact_communication_method_id),
	CONSTRAINT contact_communication_method_contact_system_fk FOREIGN KEY (contact_system_code) REFERENCES contact_system(contact_system_code) ON DELETE CASCADE,
	CONSTRAINT contact_communication_method_contact_fk FOREIGN KEY (contact_id) REFERENCES contact(contact_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX contact_communication_method_idx1 ON contact_communication_method (contact_system_code, contact_id, contact_communication_method_id);

COMMENT ON TABLE contact_communication_method IS 'Contact Communication Method';
COMMENT ON COLUMN contact_communication_method.contact_system_code IS 'Contact System Code';
COMMENT ON COLUMN contact_communication_method.contact_id IS 'Contact ID';
COMMENT ON COLUMN contact_communication_method.contact_communication_method_id IS 'Contact Communication Method ID';
COMMENT ON COLUMN contact_communication_method.communication_method_code IS 'Communication Method Code';
COMMENT ON COLUMN contact_communication_method.communication_method_label_code IS 'Communication Method Label Code';
COMMENT ON COLUMN contact_communication_method.format_value IS 'Format Value';
COMMENT ON COLUMN contact_communication_method.is_default IS 'Is Default';
COMMENT ON COLUMN contact_communication_method.status IS 'Status';
COMMENT ON COLUMN contact_communication_method.created_at IS 'Created At';
COMMENT ON COLUMN contact_communication_method.modified_at IS 'Updated At';
COMMENT ON COLUMN contact_communication_method.vers IS 'Vers';